build:
    nodes:
        coverage:
            tests:
                override:
                    -   command: vendor/bin/phpunit --coverage-clover coverage/clover.xml
                        coverage:
                            file: coverage/clover.xml
                            format: clover
            environment:
                php:
                    version: 8.0
